//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.InStore = new HashSet<InStore>();
            this.Inventory = new HashSet<Inventory>();
            this.OutStore = new HashSet<OutStore>();
        }
    
        public int Id { get; set; }
        public string Serial { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<double> Quant { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> GoodsTypeId { get; set; }
        public Nullable<int> SpecId { get; set; }
        public Nullable<int> UserInfoId { get; set; }
        public string Tag { get; set; }
    
        public virtual GoodsType GoodsType { get; set; }
        public virtual Spec Spec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InStore> InStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutStore> OutStore { get; set; }
    }
}
